Send entire url when logging type is set to domain
wakatime/browser-wakatime pull request #236
Opened 2023-10-23 14:25 UTC by jvelezpo

Fixes https://github.com/wakatime/browser-wakatime/issues/235

Send entire URL when logging type is set to `url` and mode is `whitelist` only

2023-10-24 15:41 UTC, alanhamlett commented
I don't see where it checks the logging type setting (`url` or `domain`) in the `getHeartbeat` function. Where does it decide to send only the domain vs the full url?

2023-10-24 16:17 UTC, jvelezpo commented
> I don't see where it checks the logging type setting (`url` or `domain`) in the `getHeartbeat` function. Where does it decide to send only the domain vs the full url?

We are always sending the full url, and type is set to `domain` or `url`, the BE is doing the job to convert the url value based on the type that it receives

2023-10-24 17:41 UTC, alanhamlett commented
The backed doesn't filter entity based on entity type, and for privacy reasons we only want to send the domain unless set on the client to send the full url.

2023-10-24 18:25 UTC, alanhamlett requested changes
Should only send domain when set to domain, and sent full url when set to entire url, irregardless of whitelist.

2024-08-29 10:59 UTC, alanhamlett commented
No longer necessary after refactoring in #265.

2024-08-29 10:59 UTC, closed without merging